import mysql.connector
import bcrypt

def hash_password(password: str) -> str:
    pw_bytes = password.encode('utf-8')
    hashed = bcrypt.hashpw(pw_bytes, bcrypt.gensalt())
    return hashed.decode('utf-8')

def setup_accounts():
    db = mysql.connector.connect(
        host="localhost",
        user="root",
        password="",
        database="actbayan"
    )
    cur = db.cursor()

    # 1. Populate roles if empty
    cur.execute("SELECT COUNT(*) FROM role")
    if cur.fetchone()[0] == 0:
        print("Inserting default roles into `role` table...")
        cur.execute("INSERT INTO role (role_id, role) VALUES (1, 'resident'), (2, 'lgu official'), (3, 'admin')")
        db.commit()
    else:
        print("Roles already present.")

    # Function to create an account
    def create_account(first_name, last_name, email, phone, role_id, password_str):
        # Check if already exists
        cur.execute("SELECT contact_id FROM contacts WHERE email = %s OR phone_number = %s", (email, phone))
        row = cur.fetchone()
        if row:
            print(f"Account for {email} / {phone} already exists.")
            return

        print(f"Creating {first_name} {last_name} ({email}) with role_id={role_id}...")
        
        # Calculate new account_id since accounts table is not AUTO_INCREMENT
        cur.execute("SELECT COALESCE(MAX(account_id), 0) + 1 FROM accounts")
        account_id = cur.fetchone()[0]

        # Insert into accounts
        cur.execute("""
            INSERT INTO accounts (account_id, first_name, last_name, middle_name, dob, profile_photo, account_status)
            VALUES (%s, %s, %s, '', '1990-01-01', '', 'Verified')
        """, (account_id, first_name, last_name))

        # Insert into contacts (Trigger `passcontact` auto-creates `usercreds` and `insertuser` auto-creates `credentials`)
        cur.execute("""
            INSERT INTO contacts (account_id, email, phone_number)
            VALUES (%s, %s, %s)
        """, (account_id, email, phone))
        cur.execute("SELECT MAX(contact_id) FROM contacts")
        contact_id = cur.fetchone()[0]

        # Insert password
        hashed_pw = hash_password(password_str)
        cur.execute("INSERT INTO password (password) VALUES (%s)", (hashed_pw,))
        cur.execute("SELECT MAX(pass_id) FROM password")
        pass_id = cur.fetchone()[0]

        # Get all user_ids generated by triggers for this contact
        cur.execute("SELECT user_id FROM usercreds WHERE contact_id = %s", (contact_id,))
        user_ids = [r[0] for r in cur.fetchall()]

        # Update credentials and link roles for all user_ids associated with this account
        for uid in user_ids:
            cur.execute("UPDATE credentials SET pass_id = %s, is_locked = 'N' WHERE user_id = %s", (pass_id, uid))
            cur.execute("INSERT INTO user_role (user_id, role_id) VALUES (%s, %s)", (uid, role_id))

        db.commit()
        print(f"--> Successfully created {first_name} {last_name} ({email})!")

    # 2. Create LGU Official
    create_account(
        first_name="LGU",
        last_name="Official",
        email="lgu@actbayan.gov.ph",
        phone="09222222222",
        role_id=2,          # 2 = lgu official
        password_str="lgu12345"
    )

    # 3. Create Admin
    create_account(
        first_name="System",
        last_name="Admin",
        email="admin@actbayan.gov.ph",
        phone="09111111111",
        role_id=3,          # 3 = admin
        password_str="admin12345"
    )

    cur.close()
    db.close()
    print("\nAll default accounts and roles have been set up successfully!")

if __name__ == "__main__":
    setup_accounts()
